# DPO training configuration
model:
  base_model: "meta-llama/Llama-3-8b-instruct"
  use_quantization: true
  quantization_config: "4bit"

training:
  learning_rate: 1e-6
  num_epochs: 3
  batch_size: 4
  gradient_accumulation_steps: 4
  warmup_steps: 100
  logging_steps: 10
  save_steps: 500
  eval_steps: 500

lora:
  r: 16
  alpha: 32
  dropout: 0.1
  target_modules: ["q_proj", "v_proj", "k_proj", "o_proj"]

dpo:
  beta: 0.1                  # DPO temperature parameter
  max_length: 1024          # Maximum sequence length