# Llama-3-8B DPO training configuration
model:
  base_model: "unsloth/Llama-3.1-8B-Instruct"
  use_quantization: true
  quantization_config: "4bit"

training:
  learning_rate: 1e-6  # Conservative LR for large model
  num_epochs: 3
  batch_size: 1  # Very small batch for 8B model
  gradient_accumulation_steps: 16
  warmup_steps: 100
  logging_steps: 10
  save_steps: 500
  eval_steps: 500

lora:
  r: 16
  alpha: 32
  dropout: 0.1
  target_modules: ["q_proj", "v_proj", "k_proj", "o_proj"]

dpo:
  beta: 0.1
  max_length: 1024