# Phi-3-Mini DPO training configuration
model:
  base_model: "unsloth/Phi-3-mini-4k-instruct"
  use_quantization: true
  quantization_config: "4bit"

training:
  learning_rate: 5e-6  # Moderate LR for Phi-3
  num_epochs: 3
  batch_size: 4
  gradient_accumulation_steps: 4
  warmup_steps: 75
  logging_steps: 10
  save_steps: 300
  eval_steps: 300

lora:
  r: 12  # Medium rank for efficient model
  alpha: 24
  dropout: 0.1
  target_modules: ["q_proj", "v_proj", "k_proj", "o_proj"]

dpo:
  beta: 0.1
  max_length: 1024