# TinyLlama DPO training configuration
model:
  base_model: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
  use_quantization: false  # Small model, no quantization needed
  quantization_config: "none"

training:
  learning_rate: 2e-5  # Higher LR for small model
  num_epochs: 3
  batch_size: 8  # Larger batch size for small model
  gradient_accumulation_steps: 2
  warmup_steps: 50
  logging_steps: 10
  save_steps: 200
  eval_steps: 200

lora:
  r: 8  # Smaller rank for tiny model
  alpha: 16
  dropout: 0.1
  target_modules: ["q_proj", "v_proj", "k_proj", "o_proj"]

dpo:
  beta: 0.1
  max_length: 512  # Shorter sequences for small model