# Vicuna-7B DPO training configuration
model:
  base_model: "lmsys/vicuna-7b-v1.5"
  use_quantization: false
  quantization_config: "none"

training:
  learning_rate: 1e-6  # Conservative LR for 7B model
  num_epochs: 3
  batch_size: 2  # Smaller batch for memory efficiency
  gradient_accumulation_steps: 8
  warmup_steps: 100
  logging_steps: 10
  save_steps: 500
  eval_steps: 500

lora:
  r: 16
  alpha: 32
  dropout: 0.1
  target_modules: ["q_proj", "v_proj", "k_proj", "o_proj"]

dpo:
  beta: 0.1
  max_length: 1024