"""
vLLM Email Generation Agent

This module provides email generation with:
- vLLM backend integration
- Template-based prompts
- Simple retry logic
"""

import logging
import time
from typing import Optional

from models.vllm_backend import VLLMBackend
from utils.template_manager import get_template_manager
from config.config import get_setting

logger = logging.getLogger(__name__)

class EmailAgent:
    """vLLM-based Email Generation Agent"""
    
    def __init__(self, model_id: str, dtype: str = "bfloat16", quantization: str = "experts_int8", backend_type: str = "vllm", model_key: str = None):
        """Initialize with vLLM backend"""
        self.model_id = model_id
        self.model_key = model_key  # Model configuration key
        self.model_name = model_id.split('/')[-1]
        
        # Initialize vLLM backend
        self.backend = VLLMBackend()
        
        # Get template manager
        self.template_manager = get_template_manager()
        
        # Retry settings
        self.max_retries = get_setting('max_retries', 3)
        
        logger.info(f"EmailAgent initialized with model: {self.model_name}")
    
    def generate_email(self, prompt: str, topic: str, template_id: str = "1") -> str:
        """Generate email using vLLM backend and templates"""
        start_time = time.time()
        
        try:
            # Get email template
            email_template = self.template_manager.get_email_template(template_id)
            
            # Format template with topic
            formatted_template = self.template_manager.format_template(
                email_template, 
                topic=topic
            )
            
            # Create full prompt
            full_prompt = f"{formatted_template}\n\nEmail:"
            
            # Generate with retry logic
            email_content = self._generate_with_retry(full_prompt, topic)
            
            generation_time = time.time() - start_time
            logger.info(f"Email generated in {generation_time:.2f}s for topic: {topic}")
            
            return email_content
            
        except Exception as e:
            logger.error(f"Error generating email: {e}")
            return self._generate_fallback_email(topic)
    
    def _generate_with_retry(self, prompt: str, topic: str) -> str:
        """Generate text with simple retry logic"""
        last_error = None
        
        for attempt in range(self.max_retries):
            try:
                # Generate using vLLM backend with model-specific adjustments
                model_to_use = self.model_key or self.model_id
                max_tokens = get_setting('email_max_tokens', 2048)
                temperature = get_setting('temperature', 0.7)
                
                # Adjust temperature for better output with Vicuna
                if 'vicuna' in model_to_use.lower():
                    temperature = 0.7  # Keep normal temperature for email generation
                
                result = self.backend.generate(
                    prompt=prompt,
                    model=model_to_use,
                    max_tokens=max_tokens,
                    temperature=temperature
                )
                
                if result.strip():
                    return result.strip()
                else:
                    raise Exception("Empty response from backend")
                    
            except Exception as e:
                last_error = e
                logger.warning(f"Attempt {attempt + 1} failed: {e}")
                if attempt < self.max_retries - 1:
                    time.sleep(1)  # Simple delay between retries
        
        # If all retries failed, return fallback email
        logger.warning(f"Backend generation failed, using fallback for topic: {topic}")
        return self._generate_fallback_email(topic)
    
    def _generate_fallback_email(self, topic: str) -> str:
        """Generate fallback email when vLLM is unavailable"""
        return f"""Subject: Regarding {topic}

Dear Recipient,

I hope this email finds you well. I am writing to discuss {topic}.

This email was generated using a fallback mechanism as the primary backend was unavailable. In a production environment, this would be replaced with actual LLM-generated content.

Key points regarding {topic}:
- Important discussion topic
- Requires immediate attention
- Please review and respond

Thank you for your time and consideration.

Best regards,
[Your Name]

---
Generated by EmailAgent (Fallback Mode)"""

